import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const CONTENT_DIR = path.join(process.cwd(), "src", "content", "wawasan");
const OUT = path.join(process.cwd(), "src", "lib", "generated-content.ts");

const files = readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"));

const entries = files.map((f) => {
  const slug = f.replace(/\.md$/, "");
  const raw = readFileSync(path.join(CONTENT_DIR, f), "utf8");
  return [slug, raw];
});

const lines = [
  "// AUTO-GENERATED by scripts/inline-content.mjs — jangan edit manual.",
  "// Jalankan `npm run inline-content` setelah mengubah src/content/wawasan/*.md.",
  "export const RAW_ARTICLES: Record<string, string> = {",
  ...entries.map(([slug, raw]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(raw)},`),
  "};",
  "",
];

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"));
console.log(`Generated ${entries.length} articles -> ${OUT}`);
